version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      JWT_SECRET: 2eddac82-154a-49c1-88f3-e081fb011e94
      NODE_ENV: production
      # MONGODB_URI será lido do arquivo .env (MongoDB Atlas)
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge